In [1]:
import numpy as np

In [2]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(4)
#It creates identity matrix of size 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(5)

array([0.75146938, 0.11670801, 0.29994754, 0.77192795, 0.03947355])

In [8]:

np.random.rand(5,5)

array([[0.56795495, 0.51078797, 0.26624718, 0.69874857, 0.27307548],
       [0.97306046, 0.65540637, 0.28331545, 0.19532123, 0.0876886 ],
       [0.90115588, 0.55303955, 0.86979018, 0.3834311 , 0.13576322],
       [0.15681328, 0.7344965 , 0.72725096, 0.59267473, 0.53531764],
       [0.8233519 , 0.80599505, 0.92137053, 0.5515645 , 0.12374128]])

In [9]:
np.random.randn(3)

array([-1.1673544 , -0.62697276, -0.2077768 ])

In [13]:
np.random.randint(1,100,10)
#It generates 10 random integers between 1 to 100

array([95, 51, 47, 53, 40, 39, 23, 37, 79, 37])

In [14]:
Randarr=np.random.randint(0,50,10)

In [15]:
Randarr

array([ 0, 30, 39,  6,  9,  9,  3, 48, 24, 32])

In [16]:
Randarr.reshape(2,5)

array([[ 0, 30, 39,  6,  9],
       [ 9,  3, 48, 24, 32]])

In [17]:
Randarr.max()

48

In [18]:
Randarr.min()

0

In [20]:
Randarr.argmax()

7

In [21]:
Randarr.argmin()

0

In [22]:
Randarr

array([ 0, 30, 39,  6,  9,  9,  3, 48, 24, 32])

In [24]:
Randarr.shape

(10,)

In [25]:
Mylist=[1,2,4,5]

In [26]:
Arr=np.array(Mylist)

In [27]:
Arr

array([1, 2, 4, 5])

In [29]:
from numpy.random import randint

In [30]:
randint(2,10,4)

array([2, 4, 5, 5])

In [31]:
arr=np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[9]

9

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [37]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[0:5]= 100

In [39]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
arr=np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
slice_of_arr=arr[0:6]

In [43]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
slice_of_arr[:]=99

In [46]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy=arr.copy()

In [49]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy[:]=100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [54]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d[0]

array([ 5, 10, 15])

In [56]:
arr_2d[1][1]

25

In [57]:
arr_2d[1,1]

25

In [58]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [60]:
arr=np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
bool_arr=arr>5

In [63]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr<3]

array([1, 2])

In [68]:
arr_2d=np.arange(50).reshape(5,10)

In [69]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])